global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'devsecops-api'
    # L'API expose ses metriques sur /metrics
    # host.docker.internal pointe vers la machine hote depuis un container Docker
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: /metrics
    scrape_interval: 5s
